language: python
dist: xenial

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - python setup.py test

deploy:
  - provider: pypi
    user: nextdoor
    password:
      secure: "n7GczuIQKUzBnRtO6qki3UgWgR4f0J32IrYNqb1WQR3qoBusY1CYunXNvKPTU6AVM5wP98JhQTXaDfFUUWGUGcpQWPZDbrqjszw/plL7kUggjcm2KbD+b9n7cfRzlBlTvrdFq6jO0X6zrm/HYbjr1viJEz65JDsNUfPVfLryJ+U="
    on:
      tags: true
      all_branches: true
      condition: $TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+$
    distributions: "sdist bdist_wheel"
